services:
  - type: worker
    name: wbpositionbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: wb-bot-db
          property: connectionString
      - key: SCHEDULER_ENABLED
        value: true
      - key: DEFAULT_DEVICE
        value: pc

databases:
  - name: wb-bot-db
